baseurl: https://pascoares.org
#baseurl: localhost
title: Pasco County, Florida - ARES
languageCode: en-us
paginate: 10 # Number of posts per page
# Default Theme
theme: PaperMod


menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: events
      name: Events
      url: /events/
      weight: 20
    - identifier: nets
      name: Nets
      url: /nets/
      weight: 10
    - identifier: mission
      name: Mission
      url: /mission/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40
    

params:
    homeInfoParams:
        enabled: true
    profileMode:
        enabled: true
        title: "Pasco County, Florida ARES" 
        subtitle: "Serving the Pasco county community with amateur radio"
        imageUrl: "PASCO_logo400.png"
        imageWidth: 400
        imageHeight: 400
    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    # ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true

    socialIcons:
      - name: "facebook"
        url: "https://www.facebook.com/groups/140239368312812"
      - name: "email"
        url: "mailto:n7cgc1@gmail.com"



outputs:
    home:
        - HTML
        - RSS
        - JSON
